- name: playbook
  hosts: localhost
  gather_facts: yes
  become: yes
  tasks:
  - name: install packages
    apt:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    vars:
      packages:
      - chrony
      - mosh
      - unattended-upgrades
  - name: configure chrony
    copy:
      dest: /etc/chrony.conf
      content: |
        pool       europe.pool.ntp.org iburst
        driftfile  /var/lib/chrony/drift
        makestep   10 3
        rtcsync
  - name: run chrony
    systemd:
      name: chronyd
      state: started
      enabled: true
  - name: create APT auto-upgrades configuration
    copy:
      dest: /etc/apt/apt.conf.d/20auto-upgrades
      content: |
        APT::Periodic::Update-Package-Lists "1";
        APT::Periodic::Unattended-Upgrade "1";
