- name: playbook
  hosts: localhost
  gather_facts: yes
  become: yes
  tasks:
  - name: Install packages
    dnf:
        name: "{{ packages }}"
        state: latest
    vars:
        packages:
        - dnf-automatic
        - podman
        - mosh
        - systemd-timesyncd
  - name: Configure timesyncd
    copy:
        content: |
            [Time]
            NTP=0.europe.pool.ntp.org 1.europe.pool.ntp.org 2.europe.pool.ntp.org 3.europe.pool.ntp.org
            FallbackNTP=0.rhel.pool.ntp.org 1.rhel.pool.ntp.org 2.rhel.pool.ntp.org 3.rhel.pool.ntp.org
        dest: /etc/systemd/timesyncd.conf
  - name: Run timesyncd
    systemd:
        name: systemd-timesyncd.service
        state: started
        enabled: true
  - name: Configure automatic upgrades
    copy:
        content: |
            [commands]
            upgrade_type = security
            random_sleep = 0
            download_update = yes
            apply_updates = yes
            [emitters]
            emit_via = motd
            [base]
            debuglevel = 1
        dest: /etc/dnf/automatic.conf
  - name: Run automatic upgrades
    service:
        name: dnf-automatic.timer
        state: started
        enabled: true