- hosts: all
  vars:
    postgres_host: postgres
  tasks:
  - include_vars: 
      file: encrypted_vars.yaml
    tags: always
  - include: tasks/base.yaml
  - include: tasks/backup.yaml
    tags: backup
  - include: tasks/reverse-proxy.yaml
    tags: reverse-proxy
  - include: tasks/postgres.yaml
    tags: postgres
  - include: tasks/freshrss.yaml
    tags: freshrss
  - include: tasks/linkding.yaml
    tags: linkding
  - include: tasks/planka.yaml
    tags: planka
  - include: tasks/tandoor.yaml
    tags: tandoor
  handlers:
  - name: Reload systemd daemons
    become: true
    systemd:
      daemon_reload: true
