- hosts: all
  tasks:
  - include_vars: 
      file: encrypted_vars.yaml
  - include: tasks/base.yaml
  - include: tasks/reverse-proxy.yaml
    tags: reverse-proxy
    vars:
      present: true
  - include: tasks/postgres.yaml
    tags: postgres
    vars:
      present: true
  - include: tasks/freshrss.yaml
    tags: freshrss
    vars:
      present: true
  - include: tasks/linkding.yaml
    tags: linkding
    vars:
      present: true
  - include: tasks/planka.yaml
    tags: planka
    vars:
      present: true
  - include: tasks/tandoor.yaml
    tags: tandoor
    vars:
      present: false
