# TODO use virtualenv? Maybe these should be in packer -.-
- name: Install python dependencies
  become: true
  pip:
    name:
    - docker
    - psycopg2-binary
# TODO acl setup should definitely be moved to packer
- name: Install acl
  become: true
  package:
    name: acl
    state: latest
  notify: Remount partitions
