- name: Create linkding postgres user
  no_log: true
  community.general.postgresql_user:
    login_host: "{{ postgres_host }}"
    login_password: "{{ postgres.passwords.root }}"

    name: linkding
    state: present
    password: "{{ postgres.passwords.linkding }}"
- name: Create linkding postgres database
  community.general.postgresql_db:
    login_host: "{{ postgres_host }}"
    login_password: "{{ postgres.passwords.root }}"

    name: linkding
    state: present
    owner: linkding
- name: Create linkding container
  community.docker.docker_container:
    name: linkding
    image: rogryza/linkding-postgres:1.8.5
    state: started
    container_default_behavior: compatibility
    comparisons:
      "*": strict
      labels: allow_more_present
    env:
      HOST_NAME: bookmarks.rogryza.me
      DB_PASSWORD: "{{ postgres.passwords.linkding }}"
      DB_HOST: postgres
    labels:
      traefik.enable: "true"
      traefik.port: "80"
      traefik.http.routers.bookmarks.entrypoints: websecure
      traefik.http.routers.bookmarks.rule: Host(`bookmarks.rogryza.me`)
      traefik.http.routers.bookmarks.tls: "true"
      traefik.http.routers.bookmarks.tls.certresolver: lets-encrypt
    network_mode: web
    networks:
    - name: web
    - name: postgres
    purge_networks: yes
    restart_policy: unless-stopped
# TODO manage admin user here?
