- name: "Create {{ name }} volume"
  register: backup_docker_volume
  community.docker.docker_volume:
    name: "{{ name }}"
    labels:
      me.rogryza.backup: "1"
    state: "{{ 'present' if present else 'absent' }}"
- name: "Add {{ name }} volume to backups"
  become: true
  lineinfile:
    path: /etc/restic/backup_dirs
    regexp: "^{{ name }}="
    line: "{{ name }}={{ backup_docker_volume.volume.Mountpoint }}"
    state: "{{ 'present' if present else 'absent' }}"
